config/routes.rb
Rails.application.routes.draw do

	resources :posts do
		resources :comments, only: [:create, :destroy, :update, :edit]
	end

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations',
		omniauth_callbacks: 'users/omniauth_callbacks'
	}

	root 'posts#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource #authorize! :update, @post, hace eso para todo el crud

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize! :update, @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_post
    #   @post = Post.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, html: { class: 'form-horizontal' }) do |f| %>
  <% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <%= f.label :title, 'Título', class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Título del post' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, 'Contenido', class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.text_area :content, class: 'form-control', placeholder: 'Contenido del post' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit 'Confirmar', class: 'btn btn-primary' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/posts/edit.html.erb
<legend>Editar Post</legend>

<%= render 'form', post: @post %>

<%= link_to 'Volver', posts_path, class: 'btn btn-default' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Posts</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Título</th>
      <th>Usuario</th>
      <th>Nº de comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to "#{post.title}", post %></td>
        <td><%= post.user.name %></td>
        <td><%= post.comments.count %></td>
        <% if can? :update, post %>
          <td><%= link_to 'Editar', edit_post_path(post), class: 'btn btn-sm btn-success' %></td>
        <% end %>
        <% if can? :destroy, post %>
          <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Estás seguro que deseas eliminar el Post?' }, class: 'btn btn-sm btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Post %>
  
  <%= link_to 'Nuevo Post', new_post_path, class: 'btn btn-primary' %>

<% end %>

app/views/posts/new.html.erb
<legend>Nuevo Post</legend>

<%= render 'form', post: @post %>

<%= link_to 'Volver', posts_path, class: 'btn btn-default' %>

app/views/posts/show.html.erb
<div class="text-center">
	<p id="notice"><%= notice %></p>

	<legend><h1><%= @post.title %></h1></legend>

	<p><strong>Publicado por:</strong> <%= @post.user.name %></p>

	<div class="jumbotron">
		<p>
	  <%= @post.content %>
	</p>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="well well-sm">
			<legend>Comentar:</legend>
			<%= form_with(model: [@post, Comment.new], html: { class: 'form-horizontal' }) do |f| %>
				<div class="form-group">
					<div class="col-md-12">
						<%= f.text_area :content, placeholder: 'Escribe tu comentario aquí...', class: 'form-control' %>
					</div>
				</div>
				<%= f.submit 'Comentar', class: 'btn btn-primary' %>
			<% end %>
			  
		</div>
	</div>
	<div class="col-md-8" id="comments">
		<% counter = 0 %>
		<% @comments.each do |comment| %>
			#<%= counter += 1 %>
			<div class="well well-sm" id="<%= comment.id %>">
				<strong><%= comment.user.name %>:</strong>
				<br>
				<div id="contenido<%= comment.id %>">
					<%= comment.content %>
				</div>
				
				<div class="text-right">
					<!-- Button trigger modal -->
					<%= link_to 'Editar', edit_post_comment_path(@post,comment) , data:{remote:true}, class: 'btn btn-xs btn-success' %>
					<%= link_to 'Eliminar', post_comment_path(@post,comment), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar el Comentario?', remote: true }, class: 'btn btn-xs btn-danger' %>
				</div>
			</div>
		<% end %>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Comentario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="comment_edit">
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%#= link_to 'Editar', edit_post_path(@post) %>
<%#= link_to 'Volver', posts_path, class: 'btn btn-default' %>